version: "1"
services:
  external:
    container_name: your_container
    # The name of the image that will be created when building this container
    image: yourid/image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:3000